name: production development

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to staging
      id: staging_deploy_pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_XSERVER_HOST }}
        username: ${{ secrets.PROD_XSERVER_USER }}
        key: ${{ secrets.PROD_XSERVER_SECRET }}
        script: |
          cd /var/www/vhosts/kotobum-frontend
          ./scripts/deploy.sh main